#include "stdafx.h"

const XINPUTID ARCH_CONTROLS_FORCELOAD_LONGBOW[] =  { XINPUTID_BACK , XINPUTID_START, XINPUTID_DPAD_UP };
const XINPUTID ARCH_CONTROLS_FORCELOAD_ADRIFT[] =  { XINPUTID_BACK , XINPUTID_START, XINPUTID_DPAD_RIGHT };
const XINPUTID ARCH_CONTROLS_FORCELOAD_HAVEN[] =  { XINPUTID_BACK , XINPUTID_START, XINPUTID_DPAD_DOWN };
const XINPUTID ARCH_CONTROLS_FORCELOAD_MAINMENU[] =  { XINPUTID_BACK , XINPUTID_START, XINPUTID_DPAD_LEFT };

const XINPUTID ARCH_CONTROLS_TOGGLEPRINTCAM[] =  { XINPUTID_BACK , XINPUTID_LEFT_THUMB };
const XINPUTID ARCH_CONTROLS_TOGGLEFILLMODE[] =  { XINPUTID_BACK , XINPUTID_RIGHT_THUMB };

const XINPUTID ARCH_CONTROLS_CAMERAVIEW_FIRSTPERSON[] =  { XINPUTID_LEFT_SHOULDER , XINPUTID_DPAD_UP };
const XINPUTID ARCH_CONTROLS_CAMERAVIEW_THIRDPERSON[] =  { XINPUTID_LEFT_SHOULDER , XINPUTID_DPAD_DOWN };
const XINPUTID ARCH_CONTROLS_CAMERAVIEW_FLYCAM[] =  { XINPUTID_LEFT_SHOULDER , XINPUTID_DPAD_RIGHT };
const XINPUTID ARCH_CONTROLS_CAMERAVIEW_STATIC[] =  { XINPUTID_LEFT_SHOULDER , XINPUTID_DPAD_LEFT };

const XINPUTID ARCH_CONTROLS_CAMERA_FOV_INCREASE[] =  { XINPUTID_B , XINPUTID_DPAD_DOWN };
const XINPUTID ARCH_CONTROLS_CAMERA_FOV_DECREASE[] =  { XINPUTID_B , XINPUTID_DPAD_UP };

const XINPUTID ARCH_CONTROLS_TIME_TOGGLE[] =  { XINPUTID_LEFT_THUMB , XINPUTID_RIGHT_THUMB };
const XINPUTID ARCH_CONTROLS_TIME_ACCELERATE[] =  { XINPUTID_B , XINPUTID_DPAD_RIGHT };
const XINPUTID ARCH_CONTROLS_TIME_DECELERATE[] =  { XINPUTID_B , XINPUTID_DPAD_LEFT };